### ISSUE TITLE
Setup Windows project

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#5]
- [x] Create necessary folders
- [x] Create CMakeLists.txt
- [x] Make build script run properly
- [ ] Setup Github Actions

**Comment by tonsky** [comment]
CI reference https://github.com/JetBrains/skija/blob/master/.github/workflows/build.yml

**Comment by tonsky** [comment]
<img width="496" alt="Screenshot 2021-07-01 at 10 44 26" src="https://user-images.githubusercontent.com/285292/124094718-52247e80-da59-11eb-826c-ceaa05b45b35.png">

**Comment by Solido** [comment]
Hi ! 

Can we expect a Win release soon or is it better to start with Mac package ?

Thanks Nikita

**Comment by tonsky** [comment]
Hi Robert, nice to see you here too :)

We are currently in a research stage, we have two people working on Windows/Linux for the next two months. It’s hard to predict what exactly will be done, but for sure something useful should come out of it on the other end.

**Comment by Solido** [comment]
I have postponed Jwm and Skija tinkering because my most powerful machine is on win but can bootstrap under osx.

Lot of positive vibes about the 'Jetbrain' solution that is Jwm / Skija / Compose Desktop stack.

Feels like solid foundation for the future of visual interaction. Guess I am **Hyped** !
